name: workflow to compile the docs on changes

on:
  push:
    branches:
      - master

jobs:
  compile-and-publish-doc:
    runs-on: ubuntu-22.04
    steps:
      - name: Get repo
        uses: actions/checkout@master
      - name: Checkout to doc pages
        run: |
          git fetch
          git checkout doc-pages
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install packages
        run: |
          python -m pip install -U sphinx
      - name: Build sphinx
        run: |
          sphinx-build -b html doc-sphinx/ doc-compiled/
          touch doc-compiled/.nojekyll
      - name: Commit documentation
        run: |
          git add doc-compiled/
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m 'Deploy documentation'
      - name: Show files
        run: ls -R
      - name: Git Status
        run: |
          git status
          git config --local --list
      - name: Hello world
        run: |
          echo hello world!