name: workflow to compile the docs on changes

on:
  push:
    branches:
      - master

jobs:
  compile-and-publish-doc:
    runs-on: ubuntu-22.04
    steps:
      - name: Get repo
        uses: actions/checkout@v3
      - name: Checkout to doc-pages
        run: |
          git fetch
          git checkout doc-pages
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install packages
        run: |
          python -m pip install -U sphinx
          python -m pip install -U groundwork-sphinx-theme
      - name: Build sphinx
        run: |
          sphinx-build -b html doc-sphinx/ docs/
          touch docs/.nojekyll
      - name: Commit documentation
        run: |
          git add docs/
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m 'Deploy documentation'
      - name: Push back to repo
        run: |
          git push origin doc-pages