name: workflow to compile the docs on changes

on:
  push:
    branches:
      - master

jobs:
  compile-and-publish-doc:
    runs-on: ubuntu-22.04
    steps:
      - name: Get repo
        uses: actions/checkout@master
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install packages
        run: |
          python -m pip install -U sphinx
      - name: Build sphinx
        run: |
          sphinx-build -b html doc-sphinx/ doc-compiled/
          touch doc-compiled/.nojekyll
      - name: Show files
        run: ls -R
      - name: Git Status
        run: git status
      - name: Hello world
        run: |
          echo hello world!